PayMan.Web/Areas/User/Models/TransactionViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PayMan.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PayMan.Web.Areas.User.Models
{
    public class TransactionViewModel
    {
        public int TransactionId { get; set; }

        [StringLength(35)]
        [Required(ErrorMessage = "Please enter description.")]
        public string Description { get; set; }

        [Range(0, Double.MaxValue)]
        [Display(Name = "Amount (BGN)")]
        [RegularExpression(@"^\d+.?\d{0,2}$", ErrorMessage = "Provide positive number with given up to 2 digits after the decimal separator, please.")]
        [Required(ErrorMessage = "Please enter correct amount.")]
        public decimal Amount { get; set; }

        public DateTime TimeStamp { get; set; }

        [Display(Name = "Sender's account number")]
        public string SenderAccount { get; set; }

        [Required]
        public int SenderAccountId { get; set; }
        public ICollection<PayAccountViewModel> SenderAccounts { get; set; }

        [Display(Name = "Sender's client")]
        [Required(ErrorMessage = "Please enter correct sender's client.")]
        public string SenderClient { get; set; }

        [Display(Name = "Receiver's account number")]
        [Required(ErrorMessage = "Please enter correct receiver's account.")]
        public string ReceiverAccount { get; set; }

        [Display(Name = "Receiver's client")]
        [Required(ErrorMessage = "Please enter correct receiver's client.")]
        public string ReceiverClient { get; set; }

        public string Movement { get; set; }

        public string Status { get; set; }
    }
}

PayMan.Web/Areas/User/Controllers/TransactionsController.cs
using log4net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using PayMan.Services.Contracts;
using PayMan.Services.Exceptions;
using PayMan.Services.Requests;
using PayMan.Web.Areas.User.Mappers;
using PayMan.Web.Areas.User.Models;
using PayMan.Web.Mappers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PayMan.Web.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "User")]
    public class TransactionsController : Controller
    {
        private readonly ITransactionService transactionService;
        private readonly IAccountService accountService;
        private readonly IMemoryCache cache;
        private static readonly ILog log = LogManager.GetLogger(typeof(TransactionsController));

        public TransactionsController(ITransactionService service, IAccountService accountService, IMemoryCache cache)
        {
            this.transactionService = service ?? throw new ArgumentNullException(nameof(service));
            this.accountService = accountService ?? throw new ArgumentNullException(nameof(accountService));
            this.cache = cache ?? throw new ArgumentNullException(nameof(cache));
        }

        [TempData] public string StatusMessage { get; set; }

        public async Task<IActionResult> Index(int id = 0)
        {
            var model = new TransactionHomeViewModel();
            var userId = GetLoggedUserId();

            var senderAccounts = await this.transactionService.SenderAccountNumbersAsync(int.Parse(userId));
            model.SenderAccounts = senderAccounts.Select(x => x.ToPayAccount()).ToList();

            var receiverAccounts = await this.transactionService.ReceiverAccountNumbersAsync(int.Parse(userId));
            model.ReceiverAccounts = receiverAccounts.Select(x => x.ToPayAccount()).ToList();

            model.AccountId = id;
            var loggedUserAccounts = await this.accountService.GetAccountsAsync(int.Parse(userId));
            model.LoggedUserAccounts = loggedUserAccounts.Select(x => x.ToPayAccount()).ToList();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> MakePayment(int id = 0)
        {
            var model = new TransactionViewModel();
            var accounts = await CacheAccounts();
            model.SenderAccounts = accounts;

            if (id != 0)
            {
                model.SenderAccountId = id;
            }
           
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MakePayment(TransactionViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                TempData["StatusMessage"] = "Error: Please provide valid input";
                var accounts = await CacheAccounts();
                model.SenderAccounts = accounts;
                return View(model);
            }

            try
            {
                var request = model.ToRequest();
                var transaction = await this.transactionService.SendNewTransAsync(request);

                TempData["StatusMessage"] = $"New payment was made successfully";
                return RedirectToAction(nameof(Index), new { id = transaction.TransactionId });
            }
            catch (UserException ex)
            {
                TempData["StatusMessage"] = "Error: " + ex.Message;
                var accounts = await CacheAccounts();
                model.SenderAccounts = accounts;
                return View(model);
            }
            catch (Exception e)
            {
                log.Error("Unexpected exception occured:", e);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(TransactionViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                TempData["StatusMessage"] = "Error: Please provide valid input";
                var accounts = await CacheAccounts();
                model.SenderAccounts = accounts;
                return View("MakePayment", model);
            }

            try
            {
                var request = model.ToRequest();
                var transaction = await this.transactionService.SaveNewTransAsync(request);

                TempData["StatusMessage"] = $"New transaction was saved successfully";
                return RedirectToAction(nameof(Index), new { id = transaction.TransactionId });
            }
            catch (UserException ex)
            {
                TempData["StatusMessage"] = "Error: " + ex.Message;
                var accounts = await CacheAccounts();
                model.SenderAccounts = accounts;
                return View("MakePayment", model);
            }
            catch (Exception e)
            {
                log.Error("Unexpected exception occured:", e);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var transaction = await this.transactionService.GetTransactionAsync(id);

            if (transaction is null)
            {
                return NotFound();
            }

            var model = transaction.MapFrom();
            var accounts = await CacheAccounts();
            model.SenderAccounts = accounts;

            var selection = model.SenderAccounts
                    .Where(x => x.AccountNumber == transaction.SenderAccount)
                    .FirstOrDefault();
            model.SenderClient = selection.ClientName;
            model.SenderAccountId = selection.AccountId;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TransactionViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                TempData["StatusMessage"] = "Error: Please provide valid input";
                var accounts = await CacheAccounts();
                model.SenderAccounts = accounts;
                return View(model);
            }

            try
            {
                if (id != model.TransactionId)
                {
                    TempData["StatusMessage"] = "Error: Please provide valid input";
                    return NotFound();
                }

                var request = model.ToRequest();
                await transactionService.UpdateTransactionAsync(id, request);

                TempData["StatusMessage"] = $"Transaction was successfully modified";
                return RedirectToAction(nameof(Index));
            }
            catch (UserException ex)
            {
                TempData["StatusMessage"] = "Error: " + ex.Message;
                var accounts = await CacheAccounts();
                model.SenderAccounts = accounts;
                return View(model);
            }
            catch (Exception e)
            {
                log.Error("Unexpected exception occured:", e);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Send(int id, TransactionViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                TempData["StatusMessage"] = "Error: Please provide valid input";
                var accounts = await CacheAccounts();
                model.SenderAccounts = accounts;
                return View("Index", model);
            }

            try
            {
                if (id != model.TransactionId)
                {
                    TempData["StatusMessage"] = "Error: Please provide valid input";
                    return NotFound();
                }

                var request = model.ToRequest();
                var transaction = await this.transactionService.SendSavedAsync(id, request);

                TempData["StatusMessage"] = $"Transaction was sent successfully";
                return RedirectToAction(nameof(Index));
            }
            catch (UserException ex)
            {
                TempData["StatusMessage"] = "Error: " + ex.Message;
                var accounts = await CacheAccounts();
                model.SenderAccounts = accounts;
                return View("Index", model);
            }
            catch (Exception e)
            {
                log.Error("Unexpected exception occured:", e);
                return RedirectToAction("Error", "Home");
            }
        }

        public async Task<IActionResult> SendSaved(int id)
        {
            try
            {
                var transaction = await this.transactionService.SendAsync(id);

                TempData["StatusMessage"] = $"Transaction was sent successfully";
                return RedirectToAction(nameof(Index));
            }
            catch (UserException ex)
            {
                TempData["StatusMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            catch (Exception e)
            {
                log.Error("Unexpected exception occured:", e);
                return RedirectToAction("Error", "Home");
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            var transaction = await this.transactionService.GetTransactionAsync(id);

            if (transaction == null)
            {
                throw new UserException("Transaction not available");
            }

            var model = transaction.MapFrom();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> GetSentTransactions(PayAccountViewModel senderAccountFilter,

PayMan.Web/Areas/User/Views/Transactions/Edit.cshtml
@model TransactionViewModel

@{
    ViewData["Title"] = "Edit Payment";
}

<section class="uza-about-us-area pad-up">
    <div class="row">
        <div class="col">
            <div class="container col-12 col-md-6">
                <form asp-area="User" asp-controller="Transactions" asp-action="Edit" method="post" class="border-c">
                    <div>
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="TransactionId" />
                        <input type="hidden" asp-for="TimeStamp" />
                        <input type="hidden" asp-for="Status" />
                        <input type="hidden" asp-for="Movement" />
                        <div class="text-center">
                            @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])
                        </div>
                        <div><h3>Payment Form</h3></div>
                        <hr class="c-line" />
                        <div class="form-group">
                            <label asp-for="@Model.SenderAccount"></label>
                            <select id="selected-account" class="selectpicker form-control" name="SenderAccountId">
                                @foreach (var item in @Model.SenderAccounts)
                                {
                                    <option clientName="@item.ClientName" value="@item.AccountId">@item.AccountNumber</option>
                                    if (Model.SenderAccountId == item.AccountId)
                                    {
                                        <option clientName="@item.ClientName" value="@item.AccountId" selected hidden>@item.AccountNumber</option>
                                    }
                                }
                            </select>
                            <span asp-validation-for="@Model.SenderAccount" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.SenderClient">Sender's client name: </label>
                            <input asp-for="@Model.SenderClient" id="selected-client" class="form-control" readonly />
                            <span asp-validation-for="@Model.SenderClient" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ReceiverAccount">Receiver's account number: </label>
                            <input asp-for="@Model.ReceiverAccount" id="autocomplete-payee-account" placeholder="1112223333" class="form-control">
                            <span asp-validation-for="@Model.ReceiverAccount" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ReceiverClient">Receiver'a client name: </label>
                            <input asp-for="@Model.ReceiverClient" id="selected-receiving-client" placeholder="Name..." class="form-control" readonly>
                            <span asp-validation-for="@Model.ReceiverClient" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Description">Description: </label>
                            <input asp-for="@Model.Description" placeholder="Up to 35 characters, please." class="form-control">
                            <span asp-validation-for="@Model.Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Amount">Amount: </label>
                            <input asp-for="@Model.Amount" placeholder="Within your balance." class="form-control">
                            <span asp-validation-for="@Model.Amount" class="text-danger"></span>
                        </div>
                    </div>
                    <br />
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="submit" asp-area="User" asp-controller="Transactions" asp-action="Send" asp-route-id="@Model.TransactionId" class="btn btn-primary">Send</button>
                    <br />
                </form>
            </div>
        </div>
    </div>

    <!-- Background Pattern -->
    <div class="about-bg-pattern">
        <img src="~/img/core-img/curve-2.png" alt="">
    </div>
</section>

<div class="border-line"></div>

@section Scripts{
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.8.0.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.22/jquery-ui.js"></script>
    <link rel="Stylesheet" href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.4/themes/flick/jquery-ui.css" />
    <script>
        $('#selected-account').on('change', function () {
            var itemSelected = $('#selected-account').find(":selected");
            var clientName = itemSelected.attr('clientName');

            $('#selected-client').val(clientName);
        });
    </script>

    <script>
        var globalItem;

        let timeOut;
        $(function () {
            $('#autocomplete-payee-account').autocomplete({
                source: function (input, output) {
                    clearTimeout(timeOut);
                    timeOut = setTimeout(function () {
                        $.ajax({
                            url: '@Url.Action("Complete", "Transactions")',
                            type: "POST",
                            datatype: "json",
                            data: { accountNumber: input.term},
                            success: function (data)
                            {
                                if (data)
                                {
                                    if (data.length == 0) {
                                        output([{value: "", data: "", label: "Such account number is not available."}]);
                                    }
                                    else {
                                        let items = $.map(data, function (item) {
                                            return { value: item.AccountNumber, data: item.ClientName };
                                        });
                                        output(items);
                                    }
                                }
                            }
                        });
                    }, 400);
                },
                select: function (e, ui) {
                    $('#selected-receiving-client').val(ui.item.data);
                }
            });
        });

        $('#autocomplete-payee-account').on('change', function () {
            $('#selected-receiving-client').val("");
        });
    </script>
}

PayMan.Web/Areas/User/Views/Transactions/MakePayment.cshtml
@model TransactionViewModel

@{
    ViewData["Title"] = "Make Payment";
}

<section class="uza-about-us-area pad-up">
    <div class="row">
        <div class="col">
            <div class="container col-12 col-md-6">
                <form asp-area="User" asp-controller="Transactions" asp-action="MakePayment" method="post" id="submit-form-transaction" class="border-c">
                    <div>
                        <div class="text-center">
                            @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])
                        </div>
                        <div><h3 class="text-center">Payment Form</h3></div>
                        <hr class="c-line" />
                        <div class="form-group">
                            <label asp-for="@Model.SenderAccount"></label>
                            <select id="selected-account" class="selectpicker form-control" name="SenderAccountId">
                                <option value="" selected disabled hidden></option>
                                @foreach (var item in @Model.SenderAccounts)
                                {
                                    <option clientName="@item.ClientName" value="@item.AccountId">@item.AccountNumber</option>
                                    if (Model.SenderAccountId == item.AccountId)
                                    {
                                        <option clientName="@item.ClientName" value="@item.AccountId" selected hidden>@item.AccountNumber</option>
                                    }
                                }
                            </select>
                            <span asp-validation-for="@Model.SenderAccount" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.SenderClient">Sender's client name: </label>
                            <input asp-for="@Model.SenderClient" id="selected-client" placeholder="Name..." class="form-control" readonly />
                            <span asp-validation-for="@Model.SenderClient" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ReceiverAccount">Receiver's account number: </label>
                            <input asp-for="@Model.ReceiverAccount" id="autocomplete-payee-account" placeholder="1234567890" class="form-control">
                            <span asp-validation-for="@Model.ReceiverAccount" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ReceiverClient">Receiver'a client name: </label>
                            <input asp-for="@Model.ReceiverClient" id="selected-receiving-client" placeholder="Name..." class="form-control" readonly>
                            <span asp-validation-for="@Model.ReceiverClient" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Description">Description: </label>
                            <input asp-for="@Model.Description" placeholder="Up to 35 characters, please." class="form-control">
                            <span asp-validation-for="@Model.Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Amount">Amount: </label>
                            <input asp-for="@Model.Amount" placeholder="Within your balance." class="form-control">
                            <span asp-validation-for="@Model.Amount" class="text-danger"></span>
                        </div>
                    </div>
                    <br />
                    <button type="submit" asp-area="User" asp-controller="Transactions" asp-action="Save" class="btn btn-primary">Save</button>
                    <button type="submit" class="btn btn-primary">Send</button>
                    <br />
                </form>
            </div>
        </div>
    </div>

    <!-- Background Pattern -->
    <div class="about-bg-pattern">
        <img src="~/img/core-img/curve-2.png" alt="">
    </div>
</section>

<div class="border-line"></div>

@section Scripts{
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.8.0.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.22/jquery-ui.js"></script>
    <link rel="Stylesheet" href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.4/themes/flick/jquery-ui.css" />
    <script>
        var itemSelected = $('#selected-account').find(":selected");
        var clientName = itemSelected.attr('clientName');
        $('#selected-client').val(clientName);

        $(function () {
            $('#selected-account').on('change', function () {
                var itemSelected = $('#selected-account').find(":selected");
                var clientName = itemSelected.attr('clientName');

                $('#selected-client').val(clientName);
            });
        });
    </script>

    <script>
        var globalItem;

        let timeOut;
        $(function () {
            $('#autocomplete-payee-account').autocomplete({
                source: function (input, output) {
                    clearTimeout(timeOut);
                    timeOut = setTimeout(function () {
                        $.ajax({
                            url: '@Url.Action("Complete", "Transactions")',
                            type: "POST",
                            datatype: "json",
                            data: { accountNumber: input.term},
                            success: function (data)
                            {
                                if (data)
                                {
                                    if (data.length == 0) {
                                        output([{value: "", data: "", label: "Such account number is not available."}]);
                                    }
                                    else {
                                        let items = $.map(data, function (item) {
                                            return { value: item.AccountNumber, data: item.ClientName };
                                        });
                                        output(items);
                                    }
                                }
                            }
                        });
                    }, 400);
                },      
                select: function (e, ui) {
                    $('#selected-receiving-client').val(ui.item.data);
                }
            });
        });

        $('#autocomplete-payee-account').on('change', function () {
            $('#selected-receiving-client').val("");
        });
    </script>
}