PayMan.Web/Areas/Admin/Controllers/BannerController.cs
using log4net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PayMan.Services.Contracts;
using PayMan.Services.Exceptions;
using PayMan.Web.Mappers;
using PayMan.Web.Models;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PayMan.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BannerController : Controller
    {
        private readonly IBannerService bannerService;
        private static readonly ILog log = LogManager.GetLogger(typeof(BannerController));

        public BannerController(IBannerService service)
        {
            this.bannerService = service ?? throw new ArgumentNullException(nameof(service));
        }

        [TempData]
        public string StatusMessage { get; set; }

        public async Task<IActionResult> Index()
        {
            var banners = await this.bannerService.GetAllAsync();
            var models = banners.Select(x => x.MapFrom()).ToList();

            return View(models);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var model = new CreateBannerViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(CreateBannerViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                TempData["StatusMessage"] = "Error: Please provide valid input";
                return View(model);
            }

            try
            {
                if (model.Image != null)
                {
                    if (!IsValidImage(model.Image))
                    {
                        TempData["StatusMessage"] = "Error: Please provide a .jpg or .png file smaller than 2MB";
                        return View(model);
                    }
                }

                var request = model.CreateRequest();
                var banner = await this.bannerService.AddBannerAsync(GetUploadsRoot(), request);

                TempData["StatusMessage"] = $"New banner was created successfully";
                return RedirectToAction(nameof(Index), new { id = banner.BannerId });
            }
            catch (UserException ex)
            {
                TempData["StatusMessage"] = "Error: " + ex.Message;
                return View(model);
            }
            catch (Exception e)
            {
                log.Error("Unexpected exception occured:", e);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var banner = await this.bannerService.GetBannerAsync(id);

            if (banner is null)
            {
                return NotFound();
            }

            var model = banner.MapFrom();
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditBannerViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                TempData["StatusMessage"] = "Error: Please provide valid input";
                return View(model);
            }

            try
            {
                if (model.Image != null)
                {
                    if (!IsValidImage(model.Image))
                    {
                        TempData["StatusMessage"] = "Error: Please provide a .jpg or .png file smaller than 2MB";
                        return View(model);
                    }
                }

                if (id != model.BannerId)
                {
                    TempData["StatusMessage"] = "Error: Please provide valid input";
                    return NotFound();
                }

                var request = model.EditRequest();
                await bannerService.UpdateBannerAsync(id, GetUploadsRoot(), request);

                TempData["StatusMessage"] = "Banner was successfully modified";

                return RedirectToAction(nameof(Index));
            }
            catch (UserException ex)
            {
                TempData["StatusMessage"] = "Error: " + ex.Message;
                return View(model);
            }
            catch (Exception e)
            {
                log.Error("Unexpected exception occured:", e);
                return RedirectToAction("Error", "Home");
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var banner = await bannerService.GetBannerAsync(id);

            if (banner == null)
            {
                return NotFound();
            }

            var model = banner.MapFrom();

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await bannerService.DeleteBannerAsync(id, GetUploadsRoot());

            TempData["StatusMessage"] = $"Banner was successfully deleted";

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var banner = await this.bannerService.GetBannerAsync(id);

            if (banner == null)
            {
                throw new UserException("Banner not available");
            }

            var model = banner.MapFrom();

            return View(model);
        }

        private string GetUploadsRoot()
        {
            var environment = HttpContext.RequestServices
                .GetService(typeof(IHostingEnvironment)) as IHostingEnvironment;

            return Path.Combine(environment.WebRootPath, "img", "banners");
        }

        private bool IsValidImage(IFormFile image)
        {
            var type = image.ContentType;
            if (type != "image/png" && type != "image/jpg" && type != "image/jpeg")
            {
                return false;
            }

            return image.Length <= 2048 * 2048;
        }
    }
}

PayMan.Web/Areas/Admin/Controllers/ClientController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PayMan.Data.Models;
using PayMan.Services.Contracts;
using PayMan.Services.DTOs;
using PayMan.Web.Areas.Admin.Models;
using PayMan.Web.Mappers;
using PayMan.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PayMan.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ClientController : Controller
    {
        private readonly IClientService clientService;
        private readonly IAccountService accountService;
        private readonly IUserService userService;


        public ClientController(IClientService clientService, IAccountService accountService, IUserService userService)
        {
            this.clientService = clientService;
            this.accountService = accountService;
            this.userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AllClients()
        {
            var draw = Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            int totalRecord = this.clientService.GetTotalClientsCount();
            var clients = await this.clientService.GetClientsAsync(skip, pageSize, searchValue);
            var model = clients.Select(x => x.MapFrom()).ToList();

            return Json(new { draw = draw, recordsFiltered = totalRecord, recordsTotal = totalRecord, data = model });
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClientViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return BadRequest("Please submit valid form!");
            }

            try
            {
                if (await clientService.ExistClientAsync(model.ClientName))
                {
                    return BadRequest("Client name already exists!");
                }
                var client = await this.clientService.CreateClientAsync(model.ClientName);
                var clientView = client.MapFrom();
                return Json(clientView);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                return View(model);
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            var client = await this.clientService.GetClientByIdAsync(id);

            if (client == null)
            {
                return RedirectToAction("Error","Home");
            }

            var accounts = await this.accountService.GetClientAccountsAsync(id);

            if (accounts==null)
            {
                return BadRequest("There is no accounts!");
            }

            var users = await this.clientService.GetUsersClientsAsync(id);
            if (users == null)
            {
                return BadRequest("There is no users!");
            }
            client.Accounts = accounts;
            client.UsersClients = users;

            var model = new ClientDetailsViewModel();
            model.Client = client.MapFrom();
            var accountViewModels = accounts.Select(a => a.MapFrom()).ToList();
            model.Client.AccountViewModels = accountViewModels;
            return View(model);
        }

        public async Task<IActionResult> ClientUsers(int id)
        {
            var client = await this.clientService.GetClientByIdAsync(id);
            var usersClient = await this.clientService.GetUsersClientsAsync(id);
            client.UsersClients = usersClient;

            var viewModel = new ClientDetailsViewModel();
            viewModel.Client = client.MapFrom();
            return PartialView("_ClientPartial", viewModel);
        }


        [HttpGet]
        public IActionResult AddUser()
        {
            return View("Details");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUser(ClientDetailsViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return BadRequest("Please submit valid form!");
            }

            try
            {
                var user = await this.clientService.AddUserToClient(model.UserName, model.Client.ClientId);

                return Ok($"User \"{user.UserName}\" was added succesfully!");
            }
            catch (Exception)
            {
                return BadRequest("This user can not be added! Please check username!");
            }
        }

        public async Task<IActionResult> RemoveUser(int id,int clientId)
        {
            var client = await this.clientService.GetClientByIdAsync(clientId);
            if (client==null)
            {
                return BadRequest("Client does not exist");
            }
            try
            {
                var user = await clientService.RemoveUserAsync(id, clientId);

                return Ok();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public async Task<IActionResult> Search(string term)
        {
            var names = await this.userService.GetUsersNameAsync(term);
            return Json(names);
        }
    }
}

PayMan.Web/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PayMan.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class MenuController : Controller
    {        
        public IActionResult Index()
        {
            return View();
        }
    }
}

PayMan.Web/Areas/User/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PayMan.Services.Contracts;
using PayMan.Web.Areas.User.Models;
using PayMan.Web.Models;

namespace PayMan.Web.Areas.User.Controllers
{

    [Area("User")]
    [Authorize(Roles = "User")]
    public class AccountsController : Controller
    {

        private readonly IAccountService accountService;
        private readonly IUserService userService;

        public AccountsController(IAccountService accountService, IUserService userService)
        {
            this.accountService = accountService ?? throw new ArgumentNullException(nameof(accountService));
            this.userService = userService ?? throw new ArgumentNullException(nameof(userService));
        }

        public async Task<IActionResult> Index()
        {
            var userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            var accounts = await this.accountService.GetUserAccountsAsync(userId);
            var model = new AccountViewModel();
            model.UsersAccounts = accounts;

            return View(model);
        }

        public async Task<IActionResult> GetAccountsBalance()
        {
            var userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            var accounts = await this.accountService.GetUserAccountsAsync(userId);

            ICollection<AccountBalanceViewModel> model = accounts.Select(x => new AccountBalanceViewModel()
            {
                AccountNumber = x.Account.AccountNumber,
                Balance = x.Account.Balance,
                NickName = x.Nickname
            }).ToList();

            return Json(model);
        }

        [HttpGet]
        public IActionResult EditNickname(int id)
        {
            var model = new AccountBalanceViewModel();

            return PartialView("_EditNicknamePartial", model);

        }

        [HttpPost]
        public async Task<IActionResult> EditNickname(int id, string name)
        {
            var userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            var account = await this.accountService.EditNickNameAsync(id, userId, name);

            return RedirectToAction("Index");
        }
    }
}

PayMan.Web/Areas/Admin/Views/Shared/_AccountInfoPartial.cshtml
@model AccountViewModel
<!-- Modal -->
<div>
    <div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addContactLabel">Account's users</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table">
                        <thead class="bg-gradient-success">
                            <tr>
                                <th>Users</th>
                                <th>Manage</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var users in Model.UsersAccounts)
                            {
                                <tr>

                                    <td>
                                        <h6>@users.User.UserName</h6>
                                    </td>
                                    <td>
                                        <button class="btn-outline-danger" data-toggle="remove-user" userId="@users.UserId" accountId="@users.AccountId">
                                            Remove user from account
                                        </button>

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

PayMan.Web/Areas/Admin/Views/Shared/_AccountPartial.cshtml
@model ClientDetailsViewModel

<div id="modal-acc-placeholder"></div>
<div id="modal-acc-add-user"></div>

<div class="table-responsive table-hover">
    <table id="client-accounts-table" class="table">
        <thead class="bg-gradient-info">
            <tr role="row">
                <th>
                    <h5>AccountNumber</h5>
                </th>
                <th>
                    <h5>Balance</h5>
                </th>
                <th>
                    <h5><i class="icon_pencil-edit"></i> Manage</h5>
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var account in Model.Client.Accounts)
            {
                <tr>
                    <td>
                        <h6>@account.AccountNumber</h6>
                    </td>
                    <td>
                        <h6>BGN @account.Balance</h6>
                    </td>
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn-sm bg-gradient-success" data-toggle="acc-details-modal" acc-id="@account.AccountId" data-url="@Url.Action("Details","Accounts")">
                            Details
                        </button>
                        <button type="button" class="btn-sm bg-gradient-info" data-toggle="add-user-modal" client-id="@Model.Client.ClientId" acc-id="@account.AccountId" data-url="@Url.Action("ClientUsersDetails","Accounts")">
                            Add user
                        </button>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

PayMan.Web/Areas/Admin/Views/Shared/_AddUserPartial.cshtml
@model ClientDetailsViewModel


<div class="stretch-card grid-margin">
    <div class="card card-img-holder text-white">
        <div class="card-body">
            <div><h3 class="text-info"><i class="icon_clipboard"></i> Add User to client</h3></div>
            <form id="add-user-form" asp-controller="Client" asp-action="AddUser" clientId="@Model.Client.ClientId">
                <div class="form-group">
                    <input asp-for="@Model.Client.ClientId" type="hidden">
                </div>
                <div class="form-group">
                    <input asp-for="@Model.Client.ClientName" type="hidden">
                </div>
                <div class="form-group">
                    <label asp-for="@Model.UserName"></label>
                    <input asp-for="@Model.UserName" type="text" id="username" class="form-control" placeholder="Enter username" />
                    <span asp-validation-for="@Model.UserName" id="message" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn bg-gradient-success">Add to client</button>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts{

    @await Html.PartialAsync("_ValidationScriptsPartial")
}

PayMan.Web/Areas/Admin/Views/Shared/_BannerDetailsPartial.cshtml
@model EditBannerViewModel

<div class="col-4">
    <img class="img-rounded small-size" src="~/img/banners/@(Model.ImageName)">
</div>
<div class="col">
    <h5 class="text-justify"><strong>URL: </strong><a href="@Model.URL" target="_blank">@Model.URL</a></h5>
    <h5 class="text-justify"><strong>Start Validity: </strong>@Model.StartValidity</h5>
    <h5 class="text-justify"><strong>End Validity: </strong>@Model.EndValidity</h5>
</div>

PayMan.Web/Areas/Admin/Views/Shared/_ClientPartial.cshtml
@model ClientDetailsViewModel

<table id="user-clients-table" class="table table-hover">
    <thead class="bg-gradient-success">
        <tr>
            <th>
                <h5><i class="icon_profile"></i> Username</h5>
            </th>
            <th>
                <h5>Name</h5>
            </th>
            <th>
                <h5><i class="icon_pencil-edit"></i> Manage</h5>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Client.UsersClients)
        {
            <tr>
                <td>
                    <h6>@user.User.UserName</h6>
                </td>
                <td>
                    <h6>@user.User.FullName</h6>
                </td>
                <td>
                    <a id="remove-user" userId="@user.UserId"  class="text-danger text-right" clientId="@Model.Client.ClientId"> <i class="icon_close"></i> Remove from client</a>
                </td>
            </tr>
        }
    </tbody>
</table>

PayMan.Web/Areas/Admin/Views/Shared/_ClientUsersInfo.cshtml
@model AccountViewModel
<!-- Modal -->
<div>
    <div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addContactLabel">Client's users</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table id="acc-user-tbl" class="table">
                        <thead class="bg-gradient-success">
                            <tr>
                                <th>Users</th>
                                <th>Manage</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var users in Model.ClientUsers)
                            {
                                <tr>

                                    <td>
                                        <h6>@users.User.UserName</h6>
                                    </td>
                                    <td>
                                        <button class="btn-outline-info" data-toggle="add-user" userId="@users.UserId" accountId="@Model.AccountId">
                                            Add user to account
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

PayMan.Web/Areas/Admin/Views/Shared/_CreateAccountPartial.cshtml
@model ClientDetailsViewModel

@{ Layout = null; }


<div class="stretch-card grid-margin">
    <div class="card card-img-holder text-white">
        <div class="card-body">
            <div><h3 class="text-info"><i class="icon_clipboard"></i> Create account form</h3></div>
            <form id="add-account-form" asp-controller="Accounts" asp-action="Create" clientId="@Model.Client.ClientId">
                <div class="form-group">
                    <input asp-for="@Model.Client.ClientId" type="hidden">
                </div>
                <div class="form-group">
                    <input asp-for="@Model.Client.ClientName" type="hidden">
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Balance"></label>
                    <input asp-for="@Model.Balance" type="text" value="10000" id="username" class="form-control" placeholder="Enter amount (BGN)" />
                    <span asp-validation-for="@Model.Balance" id="message" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn bg-gradient-info">Create account</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

PayMan.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    <title>PayMan: @ViewData["Title"]</title>

    <!-- Favicon -->
    <link rel="icon" href="~/img/fav.png">

    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/animate.css" rel="stylesheet" />
    <link href="~/css/owl.carousel.min.css" rel="stylesheet" />

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="/style.css">
    <link rel="stylesheet" href="/css/custom.css">
    <link rel="stylesheet" href="~/css/custom2.css">



    <!--Autocomplete search-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">

</head>

<body>
    <!-- Preloader -->
    <div id="preloader">
        <div class="wrapper">
            <div class="cssload-loader"></div>
        </div>
    </div>

    <!-- ***** Header Area Start ***** -->
    <header class="header-area">
        <!-- Main Header Start -->
        <div class="main-header-area">
            <div class="classy-nav-container breakpoint-off">
                <!-- Classy Menu -->
                <nav class="classy-navbar justify-content-between" id="uzaNav">

                    <!-- Logo -->
                    <a asp-controller="Menu" asp-action="Index" class="nav-brand">
                        <span class="text-capitalize"><img src="~/img/fav.png" />PAYMAN</span>
                    </a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">

                        <span class="navbarToggler"></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">
                        <!-- Menu Close Button -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->

                        <div class="classynav">
                            <ul id="nav">
                                <li><a asp-controller="Manage" asp-action="Index" class="uza-btn">Users</a></li>
                                <li><a asp-controller="Client" asp-action="Index" class="uza-btn">Clients</a></li>
                                <li><a asp-controller="Banner" asp-action="Index" class="uza-btn">Banners</a></li>
                            </ul>

                            <!-- Logout -->
                            <div class="login-register-btn mx-3">
                                <a asp-controller="Home" asp-action="Logout">Log out</a>
                            </div>
                        </div>
                        <!-- Nav End -->
                    </div>
                </nav>
            </div>
        </div>
    </header>

    <!-- ***** Header Area End ***** -->
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- ******* All JS Files ******* -->
    <!-- jQuery js -->
    <script src="/js/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Popper js -->
    <script src="/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- All js -->
    <script src="/js/uza.bundle.js"></script>
    <!-- Active js -->
    <script src="/js/default-assets/active.js"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial");


    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script src="~/js/custom/site.js" asp-append-version="true" defer></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

PayMan.Web/Areas/Admin/Views/Shared/_LogInLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    <title>PayMan: @ViewData["Title"]</title>

    <!-- Favicon -->
    <link rel="icon" href="~/img/fav.png">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="/style.css">

</head>

<body>
    <!-- Preloader -->
    <div id="preloader">
        <div class="wrapper">
            <div class="cssload-loader"></div>
        </div>
    </div>

    <!-- ***** Header Area Start ***** -->
    <header class="header-area">
        <!-- Main Header Start -->
        <div class="main-header-area">
            <div class="classy-nav-container breakpoint-off">
                <!-- Classy Menu -->

            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <div class="single-welcome-slide uza-about-us-area">
        <div class="container">
            <!-- Background Curve -->
            <div class="background-curve">
                <img src="~/img/core-img/curve-1.png" alt="">
            </div>
            <!-- Background Pattern -->
            <div class="about-bg-pattern">
                <img src="~/img/core-img/curve-2.png" alt="">
            </div>
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <!-- ******* All JS Files ******* -->
    <!-- jQuery js -->
    <script src="/js/jquery.min.js"></script>
    <!-- Popper js -->
    <script src="/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- All js -->
    <script src="/js/uza.bundle.js"></script>
    <!-- Active js -->
    <script src="/js/default-assets/active.js"></script>

    @await Html.PartialAsync("_ValidationScriptsPartial");

    @RenderSection("Scripts", required: false)
</body>
</html>

PayMan.Web/Areas/Admin/Views/Shared/_StatusMessage.cshtml
@model string
@if (!string.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Model
    </div>
}